### ISSUE TITLE
env vars are not available in worker processes

### ISSUE THREAD

**Issue by bashilbers** [yoshz/symfony-docker-bootstrap#3]
Example: when doing `docker-compose exec  app bin/console doctrine:schema:create`, you are directly talking to the `app` container which has environment vars set via the compose file. 

However, if you open up a browser, the application will use a sqlite database, which can also be seen doing:
`docker-compose exec web printenv`. This does not show any env vars.

It might be that php-fpm has set clean_env to `yes` by default, and therefore all worker processes do not re-expose the complete env.

**Comment by yoshz** [comment]
The solution was indeed to set clean_env to no. 
Thanks for reporting!

**Comment by bashilbers** [comment]
👍
