### ISSUE TITLE
Composer: lock file is not up to date with the latest json

### ISSUE THREAD

**Issue by mbicknese** [yoshz/symfony-docker-bootstrap#4]
On running `composer install`, one will see the following warning message.

> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

**Comment by yoshz** [comment]
Fixed it in https://github.com/yoshz/symfony-docker-bootstrap/commit/4c0cf38590e6a5d4387ae2bc0b911c203353e587
